bootcamp/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

bootrc/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views #django의 자체 로그인 기능 사용
from . import models
from django.conf import settings
from django.conf.urls.static import static

app_name = 'bootrc'

urlpatterns = [
    path('login',auth_views.LoginView.as_view(template_name='bootrc/login.html'),name='login'), # 로그인 페이지로 이동
    path('logout',auth_views.LogoutView.as_view(),name='logout'), # 로그아웃 기능
    path('signup',views.signup,name='signup'), # 회원가입 페이지로 이동
    path('', views.index, name='index'),
    path('menu/list/', views.menu_list, name='menu_list'),
    path('rest/list/', views.rest_list, name='rest_list'),
    path('menu/create/', views.menu_create, name='menu_create'),
    path('rest/create/', views.rest_create, name='rest_create'),
    path('restmenu/list/<int:rest_rest_num>', views.restmenu_list, name='restmenu_list'),
    path('restmenu/create/<int:rest_rest_num>', views.restmenu_create, name='restmenu_create'),
    path('main/', views.main, name='main'),  # 메인 링크에서는 회원, 비회원 구분하는 페이지
    path('menu/delete/<int:menu_menu_num>', views.menu_delete, name='menu_delete'),
    path('rest/delete/<int:rest_rest_num>', views.rest_delete, name='rest_delete'),
    path('crawling', views.crawling, name='crawling'),
    path('crawling_delete', views.crawling_delete, name='crawling_delete'),
    path('recommendmenu', views.recommendmenu, name='recommendmenu'),
    path('restmenu/delete/<int:restmenu_id>', views.restmenu_delete, name='restmenu_delete'),
    path('menufavorite/', views.menu_favorite, name='menu_select'),
    path('tools',views.admin_tools,name='admin_tools'),
    path('recom_menu_test/', views.recommendmenu2, name='recommendmenu2'),
    path('app_review/', views.app_review, name='app_review'),
    path('category_select/', views.category_select, name='category_select'),
    path('rest_ranking/', views.rest_ranking, name='rest_ranking'),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bootrc/forms.py
from django import forms
from .models import Menu, Rest, RestMenu, Prefer, recentRecommended, AppReview
# 회원가입에서 사용함.
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu  # 사용할 모델
        fields = ['menu_catenum', 'menu_name2']  # MenuForm 에서 사용할 Menu모델의 2가지 속성


class RestForm(forms.ModelForm):
    class Meta:
        model = Rest  # 사용할 모델
        fields = ['rest_name', 'rest_star', 'rest_location_lat', 'rest_location_lon', 'rest_recent_user', 'rest_number_reviews']
        # RestForm에서 사용할 rest모델의 속성


class RestMenuForm(forms.ModelForm):
    class Meta:
        model = RestMenu  # 사용할 모델
        fields = ['rest_menu']  # RestForm에서 사용할 rest모델의 1가지 속성


# 회원가입 유저 폼
class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "password1", "password2")


class PreferForm(forms.ModelForm):  # 유저 메뉴 선호도 조사
    class Meta:
        model = Prefer
        fields = ['pref_like', 'pref_menu']
        widget = {'pref_menu': forms.HiddenInput()}

class recentRecommendedForm(forms.ModelForm):  # 유저 메뉴 선호도 조사
    class Meta:
        model = recentRecommended
        fields = ['rest', 'menu_name']
        widget = {'rest': forms.HiddenInput(),
                  'menu_name':forms.HiddenInput()
        }

class AppReviewForm(forms.ModelForm):
    class Meta:
        model = AppReview
        fields = ['comment', 'like_count', 'rest', 'menu_name']
        widget = {'rest': forms.HiddenInput(),
                  'menu_name': forms.HiddenInput()
        }

bootrc/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login # 로그인 및 회원가입 기능을 구현하기 위한 패키지
from .crawling import Crawling
from django.contrib.auth.decorators import login_required
from .models import Menu, Rest, RestMenu, Review, Prefer, Categories, recentRecommended, AppReview, PreferCate
from .forms import MenuForm, RestForm, RestMenuForm, UserForm, PreferForm, recentRecommendedForm, AppReviewForm
from django.contrib.auth.models import User
from time import *
import datetime
import random
import math
from haversine import haversine  # haversine 은 위도 경도로 거리 계산 함수
# pip install haversine 이 필요하다

def main(request):  # 회원, 비회원을 구분하는 페이지
    return render(request, 'bootrc/main_page.html')

"""def login(request):  # 회원(또는 가입) 로그인 페이지
    return render(request, 'bootrc/login.html')"""

def index(request):  # 버튼 메뉴들이 있는 메인 페이지
    return render(request, 'bootrc/main.html')

def menu_list(request):
    menu_list = Menu.objects.order_by('menu_num')
    context = {'menu_list': menu_list}
    return render(request, 'bootrc/menu_list.html', context)

def rest_list(request):
    rest_list = Rest.objects.order_by('rest_num')
    categories = Categories.objects.all()
    context = {'rest_list': rest_list, 'categories':categories}
    return render(request, 'bootrc/rest_list.html', context)

def recommendmenu(request):
    #restmenu = RestMenu.objects.order_by('-recommendmenu').first() #점수가 높은순 1개만 확인
    restmenu = RestMenu.objects.order_by('?').first() # 랜덤정렬 첫번째
    review = Review.objects.filter(restaurant_id=restmenu.rest_id).order_by('?').first()
    context = {'restmenu': restmenu, 'review': review}
    return render(request, 'bootrc/recommend_list.html', context)

def recommendmenu2(request):
    if request.method == 'POST':
        form = recentRecommendedForm(request.POST)
        if form.is_valid():
            recommend = form.save(commit=False)
            recommend.user = request.user
            recommend.save()
            return redirect('bootrc:index')
    else:
        form = recentRecommendedForm()

    current_user = request.user
    menu = recom_menu(current_user)
    review = Review.objects.filter(restaurant_id=menu.rest_id).order_by('?').first()
    app = AppReview.objects.filter(rest_id = menu.rest_id).order_by('?').first()
    context = {'menu': menu, 'app': app, 'form': form, 'review': review}
    return render(request, 'bootrc/recom_menu_test.html', context)


# 도보 분당 63m
def recom_menu(current_user):
    i = 0
    time = datetime.datetime.now().time()
    time_for_recent_calc = datetime.datetime.now()
    menu_list = RestMenu.objects.order_by('?')
    cate_list = PreferCate.objects.filter(user_num=current_user)
    # values_list(flat=True) 는 튜플이 아닌 리스트로 필드의 값을 반환 한다
    recent = recentRecommended.objects.filter(user=current_user).order_by('-id')
    user_prefer = Prefer.objects.filter(user_num=current_user).order_by('-id')

    while True:
        check = 0  # 가게 카테고리와 유저 카테고리가 일치 하는지 검사 일치 1, 불일치 0
        probability = 0.0  # 최종 메뉴 선별 확률( 마지막에 종합된 숫자로 확률 돌림 )
        rest_star = menu_list[i].rest.rest_star
        rest_cate = Categories.objects.filter(rest_id=menu_list[i].rest.rest_num)
        '''  # datetime.time에 시간 추가 못함 -> 현재시간과 가게 운영시간 차이로 분류
        minute = datetime.time(0, 0, 0)
        minute60 = datetime.time(0, 1, 0)
        walk = datetime.time(0, int(menu_list[i].rest.rest_distance_fromBD/63), 0)
        if menu_list[i].rest.rest_distance_fromBD/3780 > 1:
            minute += datetime.timedelta(hours=menu_list[i].rest.rest_distance_fromBD/3780)
            minute += datetime.timedelta(minutes=(menu_list[i].rest.rest_distance_fromBD % 3780)/63)
        else:
            minute += datetime.timedelta(minutes=int(menu_list[i].rest.rest_distance_fromBD/63))
    #    closing_time = datetime.strptime(menu_list[i].rest.closing_time, "%H:%M")
    #    opening_time = datetime.strptime(menu_list[i].rest.opening_time, "%H:%M")
        '''
        # datetime.time 형식
        # 가게 운영시간 기준에 맞지 않으면 다시 불러오기

        for cate in rest_cate:
            for user in cate_list:
                if user.category == cate.name:  # cate = rest_cate, user = cate_list
                    probability += 5
                    check = 1
                    continue
                else:
                    continue

        if menu_list[i].rest.closing_time < time or time < menu_list[i].rest.opening_time:
            i += 1
            if i == len(menu_list):
                return menu_list[0]
            continue
        # cate_list는 유저의 카테고리 목록
        # rest_cate는 가게의 카테고리 목록
        # 하나라도 일치 하지 않을 경우에 다시 돌림

        # cate_list는 유저의 카테고리 목록
        # rest_cate는 가게의 카테고리 목록
        # 하나라도 일치 하지 않을 경우에 다시 돌림
        if check == 0:
            i += 1
            continue

        # for user in cate_list:
        #     for cate in rest_cate:
        #         if user.category == cate.name:
        #             probability += 5
        #             check = 1
    #            if "편의점" in rest.name:
    #                check = 0
    #        if user.category in rest_cate:
    #            probability += 10
    #            check += 1
        '''
        # 도보(기본값)일 경우 가게와 떨어진 거리가 300이하인 경우 확률에 +5%
        if any(format in rest_cate for format2 in cate_list):
            i += 1
            continue
        '''
        if menu_list[i].rest.rest_distance_fromBD > 1000:
            i += 1
            continue
        elif menu_list[i].rest.rest_distance_fromBD < 300:
            probability += 5

        for count in user_prefer:
                if count.pref_like == 0:
                    probability = -200 # 절대 안걸림
                probability += count.pref_like

                # 유저가 해당 메뉴를 좋아하는 만큼 확률에 추가
                # ex) 0 일경우 절대 그 메뉴 추천 하지 않음.
                # ex) 4 만큼 좋아할 경우 (확률) + 4%

        ## 히스토리 기능
        for count in recent:
            diff_time = count.created
            day_diff = time_for_recent_calc - diff_time.replace(tzinfo=None)
            if day_diff.days < 3:
                if count.rest.rest_num == menu_list[i].rest.rest_num: # 히스토리 기능
                    probability = -200 # 절대 안걸림

        # 별점 기준 확률 조정( 낮을 수록 적은 확률 )
        probability += (rest_star ** 2) * 2
        result = random.randrange(0, 100)

        if result <= probability:
            return menu_list[i]
        else:
            i += 1
            probability = 0
        if i == len(menu_list):
            i = 0


def crawling(request):
    Crawling()
    return redirect('bootrc:index')

def restmenu_list(request, rest_rest_num):
    rest = get_object_or_404(Rest, pk=rest_rest_num)
    restmenu_list = RestMenu.objects.filter(rest_id=rest.rest_num) #RestMenu의 멤버 rest_id는 = rest객체의 rest_num
    context = {'rest': rest,'restmenu_list': restmenu_list}
    return render(request, 'bootrc/restmenu_list.html', context)


def menu_create(request):
    '''
    메뉴 등록
    '''
    if request.method == 'POST':
        form = MenuForm(request.POST)
        if form.is_valid():
            menu = form.save()
            menu.save()
            return redirect('bootrc:index')
    else:
        form = MenuForm()
    return render(request, 'bootrc/menu_form.html', {'form': form})


def rest_create(request):
    '''
    가게 등록, 거리 계산 입력
    '''
    if request.method == 'POST':
        form = RestForm(request.POST)
        if form.is_valid():
            menu = form.save()
            menu.save()
            rest_list = Rest.objects.order_by('rest_num')
            if rest_list:
                for rest in rest_list:
                    rest.distance_calc()
            return redirect('bootrc:index')
    else:
        form = RestForm()
    return render(request, 'bootrc/rest_form.html', {'form': form})


def restmenu_create(request, rest_rest_num):
    '''
    레스토랑 메뉴 등록
    '''
    rest = get_object_or_404(Rest, pk=rest_rest_num)
    if request.method == 'POST':
        form = RestMenuForm(request.POST)
        if form.is_valid():
            restmenu = form.save(commit=False)
            restmenu.rest = rest
            restmenu.recommend_calc()
            restmenu.save()
            return redirect('bootrc:restmenu_list', rest_rest_num)
    else:
        form = RestMenuForm()
    rest_menu = {'rest': rest, 'form': form}
    return render(request, 'bootrc/restmenu_form.html', rest_menu)


# 회원가입 가능 구현
def signup(request):
    if request.method == "POST":  # 요청받은 방식이 POST 방식이 아닌 경우, 회원가입 페이지로 이동함.
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # authenticate 함수는 사용자명과 비밀번호가 일치하는지 검증해 줌.

            login(request, user)  # 로그인
            return redirect('bootrc:category_select')  # 가입 완료 후, 메인 페이지로 이동함.
    else:
        form = UserForm()
    return render(request, 'bootrc/signup.html', {'form': form})

@login_required(login_url='bootrc:login')
def menu_favorite(request):  # 음식 선호도 조사
    random_menu = RestMenu.objects.order_by('?')
    category = Categories.objects.order_by('?')
    current_user = request.user
    user_prefercate = PreferCate.objects.filter(user_num=current_user)
    for cate in category:
        for user in user_prefercate:
            if user.category == cate.name:
                random_menu = RestMenu.objects.filter(rest_id=cate.rest_id).order_by('?').first()
                break
    if request.method == "POST":
        form = PreferForm(request.POST)
        if form.is_valid():
            prefer = form.save(commit=False)
            prefer.user_num = current_user
            prefer.save()

            form = PreferForm()
            context = {'random_menu': random_menu, 'current_user': current_user, 'form': form, 'user_prefercate': user_prefercate}

templates/bootrc/admin.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
    <a href="{% url 'bootrc:menu_create' %}" class="btn btn-primary">메뉴 만들기</a>
    <a href="{% url 'bootrc:menu_list' %}" class="btn btn-primary">메뉴 목록보기</a>
    <a href="{% url 'bootrc:menu_select' %}" class="btn btn-primary">메뉴 선호 설정</a>
    <a href="{% url 'bootrc:category_select' %}" class="btn btn-primary">카테고리 선호 설정</a>
    <a href="{% url 'bootrc:rest_create' %}" class="btn btn-primary">가게 만들기</a>
    <a href="{% url 'bootrc:rest_list' %}" class="btn btn-primary">가게 목록보기</a>
    <a href="{% url 'bootrc:crawling' %}" class="btn btn-primary">크롤링</a>
    <a href="{% url 'bootrc:crawling_delete' %}" class="btn btn-primary">크롤링 삭제</a>
    <a href="{% url 'bootrc:recommendmenu' %}" class="btn btn-primary">메뉴 추천</a>
    <a href="{% url 'bootrc:recommendmenu2' %}" class="btn btn-primary">추천 받기 테스트</a>
    <a href="{% url 'bootrc:app_review' %}" class="btn btn-primary">리뷰 작성하기</a>
    <a href="{% url 'bootrc:rest_ranking' %}" class="btn btn-primary">맛집 랭크</a>
    <span><strong> 현재 로그인 : {{user.username}} 님 </strong></span>
{% else %}
    <div class="notice">이 페이지에 접근할 권한이 없습니다.<br/>로그인 후 이용하여 주십시오.<br/></div>
    <a href="{% url 'bootrc:login' %}" class="btn btn-primary">로그인</a>
{% endif %}
{% endblock %}

templates/bootrc/login.html
{% extends "base.html" %}
{% block content %}
<script language="JavaScript1.2">
    top.document.title=top.document.title+"-로그인";
</script>
<!--
index = 메뉴목록 있는 메인 페이지로 이동
<a href="{% url 'bootrc:index' %}" class="btn btn-primary">메인 화면 이동</a>
<a href="{% url 'bootrc:signup' %}" class="btn btn-primary">회원가입</a>
-->
<!-- 로그인 창 구성 : 개발중 -->
<div class="text-center">
<main class="form-signin">
  <form method="post" class="post-form" action="{% url 'bootrc:login' %}">
    {%csrf_token%}
    {%include "bootrc/form-error.html"%}
    <h1 class="h3 mb-3 fw-normal">로그인 해주세요!</h1>
    <div class="form-floating m10">
      <label for="username">아이디</label>
      <input  type="text" class="form-control login_style" name="username" id="username" value="{{form.username.value|default_if_none:''}}" placeholder="아이디"
      style="width:300px;text-align:center">
    </div>
    <div class="form-floating m10">
      <label for="password">패스워드</label>
      <input type="password" class="form-control login_style" name="password" id="password" value="{{form.password.value|default_if_none:''}}" placeholder="패스워드"
      style="width:300px;text-align:center">
    </div>
    <button class="w-10 btn btn-lg btn-primary m10"  type="submit">로그인</button>
  </form>
</main>
</div>
{% endblock %}

templates/bootrc/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        {% if user.is_authenticated %}
        <a href="{% url 'bootrc:recommendmenu2' %}"><img alt="추천 결과 확인" src="{% static '1.png' %}" class="main_button"></a>
        <a href="{% url 'bootrc:menu_select' %}"><img alt="선호 메뉴 설정" src="{% static '4.png' %}" class="main_button"></a>
        <a href="{% url 'bootrc:category_select' %}"><img alt="선호 카테고리 설정" src="{% static '5.png' %}" class="main_button"></a>
        <a href="{% url 'bootrc:rest_ranking' %}"><img alt="맛집 랭킹" src="{% static '2.png' %}" class="main_button"></a>
        <a href="app_review"><img alt="리뷰 남기기" src="{% static '3.png' %}" class="main_button"></a>
        {% else %}
        <div class="main_no_login"><a href="login">로그인</a>을 하시면 다양한 기능을 이용할 수 있습니다.</div>
        <a href="javascript:void(0);" onclick="alert('로그인 후 이용해주세요!');"><img alt="추천 결과 확인" src="{% static '1.png' %}" class="main_button"></a>
        <a href="javascript:void(0);" onclick="alert('로그인 후 이용해주세요!');"><img alt="선호 메뉴 설정" src="{% static '4.png' %}" class="main_button"></a>
        <a href="javascript:void(0);" onclick="alert('로그인 후 이용해주세요!');"><img alt="선호 카테고리 설정" src="{% static '5.png' %}" class="main_button"></a>
        <a href="javascript:void(0);" onclick="alert('로그인 후 이용해주세요!');"><img alt="맛집 랭킹" src="{% static '2.png' %}" class="main_button"></a>
        <a href="javascript:void(0);" onclick="alert('로그인 후 이용해주세요!');"><img alt="리뷰 남기기" src="{% static '3.png' %}" class="main_button"></a>
        {% endif %}
{% endblock %}

templates/bootrc/menu_list.html
{% extends 'base.html' %}
{% load static %}
1<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>메뉴 번호</th>
            <th>카테고리 번호</th>
            <th>메뉴</th>
            <th>삭제</th>
        </tr>
        </thead>
        <tbody>
        {% if menu_list %}
        {% for menu in menu_list %}
        <tr>
            <td>{{ menu.menu_num }}</td>
            <td>{{ menu.menu_catenum }}</td>
            <td>{{ menu.menu_name2 }}</td>
            <td><a href="#" data-uri="{% url 'bootrc:menu_delete' menu.menu_num %}"
               class="delete btn btn-sm btn-outline-secondary">삭제</a></td>
<!--delete href를 #으로 지정하여 확인창을 JS로 구현하기 위해-->
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">메뉴가 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
<!--    <a href="{% url 'bootrc:menu_create' %}" class="btn btn-primary">메뉴 만들기</a>-->
</div>
{% endblock %}
<!--JS-->
{% block script %}
<script type="text/javascript">
$(document).ready(function(){
    $(".delete").on('click', function(){
        if(confirm("정말로 삭제하시겠습니까?")){
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}

templates/bootrc/recom_menu_test.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!--
<div style="position: fixed;z-index: -1"><img src ="/images/{{ menu.rest.back_image }}/"></div>
-->
<div class="container pt-5">
    {% if menu %}
    <h3 class="text-center">{{user.username}}님에게 이 식당을 추천드려요!</h3>
    <div class="rest_img">
        <img src ="/images/{{ menu.rest.image }}/">
    </div>
    <div class="py-3 text-center alert alert-info" role="alert">
        <h4>추천 맛집 : <strong>{{ menu.rest.rest_name}}</strong></h4>
        <h4>추천 메뉴 : <strong>{{ menu.rest_menu }}</strong></h4>
        <h4>별점 : <strong>{{ menu.rest.rest_star}}점</strong></h4>
        <h4>운영 시간 : <strong>{{ menu.rest.opening_time }} ~ {{ menu.rest.closing_time }}</strong></h4>
        <h4>전주대 구정문에서의 거리 : <strong>{{ menu.rest.rest_distance_fromBD }}m</strong></h4>
        {% if menu.rest.phone_number %}
        <h4>가게 번호 : <strong>{{ menu.rest.phone_number }}</strong></h4>
        {% endif %}
        <h4>주소 : <strong>{{ menu.rest.address }}</strong></h4>
        {% if review.comment %}
        <h4>리뷰 메뉴 : <strong>{{ review.menu_name }}</strong></h4>
        <h4>리뷰(요기요): <strong>{{ review.comment }}</strong></h4>
        {% endif %}
        {% if app.comment %}
        <h4>앱 리뷰 : <strong>{{ app.comment }}</strong></h4>
        {% endif %}
    </div>
    <div style="position: relative" >
    <div id="map" style="height:350px;"></div><div style="clear: both;"></div>
    <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=e484d23c5256509bb404015ea2639044"></script>
        <script>
            var container = document.getElementById('map');
            var options = {
                center: new kakao.maps.LatLng( {{menu.rest.rest_location_lat}}, {{menu.rest.rest_location_lon}}),
            level: 3
            };
            var map = new kakao.maps.Map(container, options);

            var markerPosition  = new kakao.maps.LatLng( {{menu.rest.rest_location_lat}}, {{menu.rest.rest_location_lon}});

            // 마커를 생성합니다
            var marker = new kakao.maps.Marker({
                position: markerPosition
            });

            // 마커가 지도 위에 표시되도록 설정합니다
            marker.setMap(map);

            var iwContent = '<a href="https://www.yogiyo.co.kr/mobile/#/{{menu.rest.yogiyo_id}}" style="display:inline-block; width:160px; height:35px; padding:5px;">{{restmenu.rest.rest_name}}요기요에서 확인하기</a>';
            // 링크는 잘 작동하는데 문제는 div가 작동을 안함 해결해줘요!
            //'<div style="background-color: gold; padding:10px; width: 300px; height: auto; cursor: pointer;" onClick="location.href="https://www.yogiyo.co.kr/mobile/#/{{restmenu.rest.yogiyo_id}}";">요기요 링크!</div>'
            // 인포윈도우에 표출될 내용으로 HTML 문자열이나 document element가 가능합니다

            // 인포윈도우를 생성합니다
            var infowindow = new kakao.maps.InfoWindow({
                content : iwContent
            });

            // 마커에 마우스오버 이벤트를 등록합니다
            kakao.maps.event.addListener(marker, 'mouseover', function() {
                // 마커에 마우스오버 이벤트가 발생하면 인포윈도우를 마커위에 표시합니다
                infowindow.open(map, marker);
            });

            // 마커에 마우스아웃 이벤트를 등록합니다
            kakao.maps.event.addListener(marker, 'mouseout', function() {
                // 마커에 마우스아웃 이벤트가 발생하면 인포윈도우를 제거합니다
                // infowindow.close();
            });
        </script>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <div class="form-group">
            <label for="rest"></label>
            <td><label><input type="hidden" name="rest" id="rest"
                               value="{{ menu.rest.rest_num }}"></label></td>
        </div>
        <div class="form-group">
            <label for="menu_name"></label>
            <td><label><input type="hidden" name="menu_name" id="menu_name"
                              value="{{ menu.id }}"></label></td>
        </div>
        <button type="submit" class="btn btn-primary" style="display: block;
                    position: absolute; top:82%; left:46%" >확인</button>
        <!--<a href="{% url 'bootrc:recommendmenu2' %}" class="btn btn-primary">다시 추천받기</a>-->
    </form>
    </div>
    {% else %}
    <h3 class="pt-5 text-center">메뉴가 없네요...</h3>
    {% endif %}
</div>

{% endblock %}

templates/bootrc/restmenu_list.html
{% extends 'base.html' %}
{% load static %}
1<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>가게 이름</th>
            <th>메뉴 이름</th>
            <th>추천 점수</th>
            <th>삭제</th>
        </tr>
        </thead>
        <tbody>
        {% if restmenu_list %}
        {% for restmenu in restmenu_list %}
        <tr>
            <td>{{ restmenu.rest.rest_num }}</td>
            <td>{{ restmenu.rest.rest_name }}</td>
            <td>{{ restmenu.rest_menu }}</td>
            <td>{{ restmenu.rest_recommend}}</td>
            <td><a href="#" data-uri="{% url 'bootrc:restmenu_delete' restmenu.id %}"
               class="delete btn btn-sm btn-outline-secondary">삭제</a></td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <a href="{% url 'bootrc:restmenu_create' rest.rest_num %}" class="btn btn-primary">메뉴 만들기</a>
</div>
{% endblock %}
<!--JS-->
{% block script %}
<script type="text/javascript">
$(document).ready(function(){
    $(".delete").on('click', function(){
        if(confirm("정말로 삭제하시겠습니까?")){
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}